### ISSUE TITLE
Helm chart issue with crashing pod for aidboxdb

### ISSUE THREAD

**Issue by rajb-duplo** [Aidbox/helm-charts#7]
Hey Health Samurai Team, I tried to install helm chart for aidboxdb but its getting error saying "mkdir: cannot create directory ‘/data/pg’: Permission denied". I also used few security contexts but that also didn't help.

```
securityContext:
  allowPrivilegeEscalation: true
  runAsNonRoot: true 
  runAsUser: 101
  runAsGroup: 103
```
  
  can you please check once if any restriction has been added to db config through docker file?

**Comment by faridco** [comment]
the following helm values snippet should help
```yaml
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 103
  fsGroup: 103
  fsGroupChangePolicy: "OnRootMismatch"
```
